import os
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

_api_key    = os.getenv("GEMINI_API_KEY", "")
_model_name = os.getenv("GEMINI_MODEL", "gemini-2.0-flash-exp")

_SYSTEM_PROMPT = """
You are CropSense AI, an expert agricultural data analyst assistant.
You help users understand crop yield predictions generated by an XGBoost machine learning model.

Your role:
- Explain predicted yield values clearly (hg/ha and tonnes/ha).
- Provide insights about what factors (rainfall, temperature, pesticides) likely influenced the prediction.
- Compare to typical global yields for the crop.
- Offer practical agricultural recommendations when asked.
- Keep responses concise, friendly, and informative.
- Always respond in the same language the user uses (Indonesian or English).

Important: You only have access to the prediction data provided in the conversation context.
Do not fabricate historical data or make up specific statistics beyond general agricultural knowledge.
"""


def chat_with_gemini(message: str, history: list, prediction_context: dict = None) -> str:
    """Send a message to Gemini with session history and optional prediction context."""
    if not _api_key or _api_key == "your_gemini_api_key_here":
        return "⚠️ Gemini API key belum dikonfigurasi. Tambahkan GEMINI_API_KEY pada file .env di backend."

    client = genai.Client(api_key=_api_key)

    # Build chat history in google-genai format
    gemini_history = []
    for msg in history:
        role = "user" if msg["role"] == "user" else "model"
        gemini_history.append(
            types.Content(role=role, parts=[types.Part(text=msg["content"])])
        )

    # Inject prediction context into message
    context_prefix = ""
    if prediction_context:
        context_prefix = (
            f"[Prediction Context]\n"
            f"  Area     : {prediction_context.get('area')}\n"
            f"  Crop     : {prediction_context.get('item')}\n"
            f"  Year     : {prediction_context.get('year')}\n"
            f"  Yield    : {prediction_context.get('predicted_yield_hg_ha'):,.2f} hg/ha "
            f"({prediction_context.get('predicted_yield_tonnes_ha'):.4f} tonnes/ha)\n"
            f"  Model R² : {prediction_context.get('model_r2')}\n\n"
        )

    full_message = context_prefix + message

    response = client.models.generate_content(
        model=_model_name,
        contents=gemini_history + [types.Content(role="user", parts=[types.Part(text=full_message)])],
        config=types.GenerateContentConfig(system_instruction=_SYSTEM_PROMPT),
    )
    return response.text
